version: "3.8" # This is the Docker Compose file format version.

services: # Defines the different services (containers) your app will run.

  web: # This is the first service — your Flask app container.
    build: . # Build image from Dockerfile in current directory
    expose:
      - "5002"  # Exposes port 5002 inside the container (not published to host)
    depends_on:
      - redis  # Start web only after redis is ready

  redis: # Redis database container
    image: "redis:latest" # Pull latest Redis image from Docker Hub
    ports:
      - "6379:6379" # Maps port 6379 on host → port 6379 in container
    volumes:
      - redis-data:/data # Persist /data using named volume redis-data
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  nginx:
    image: nginx:latest
    ports:
      - "5002:5002" # Publish container port 5002 to host port 5002
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes: # Declare named volumes here (not under services)
  redis-data: # Docker Compose will create/manage this volume for you